name: nu_app
version: 1.0.0
publish_to: 'none'
description: A simple University Directory App demo.

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.5
  url_launcher: ^6.2.6
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/nu-logo.png
    - assets/img.png
    - assets/bangladesh-railway.png
    - assets/habib_nu.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/nu-logo.png"
